/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Center: typeof import('./src/components/center.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Officereview: typeof import('./src/components/officereview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tufour: typeof import('./src/components/tufour/index.vue')['default']
    Tuone: typeof import('./src/components/tuone/index.vue')['default']
    Tuthree: typeof import('./src/components/tuthree/index.vue')['default']
    Tutwo: typeof import('./src/components/tutwo/index.vue')['default']
  }
}
